title: Ting Radio
default_language: en
url: https://vonzen.github.io
baseurl: /TingRadio
appstore_link: https://apps.apple.com/app/id6451428572
ios_app_id: 6451428572
email_address: VonzenApp@outlook.com
markdown: kramdown
plugins:
  - jekyll-sitemap
collections:
  pages:
    output: true
    permalink: /:path/
exclude:
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - docs
  - scripts
  - vendor
  - .DS_Store
  - assets/.DS_Store
  - main.scss
  - assets/screenshot
  - assets/black.png
  - assets/blue.png
  - assets/coral.png
  - assets/white.png
  - assets/yellow.png
  - assets/headerimage.png
  - assets/playstore.png
