#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6451428572                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Ting Radio                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Listen radio form the world.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Vonzen                                
your_link                                 :                      
your_city                                 :                                 
email_address                             : VonzenApp@outlook.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Extensive Content Selection
    description                           : We offers a wide range of rich content, covering various themes and styles of radio channels. Users can choose from different types of programs based on their interests, including music, news, entertainment, education, and specialized knowledge, catering to diverse auditory needs.
    fontawesome_icon_name                 : globe
    
  - title                                 : Personalized Recommendation System
    description                           : Through an intelligent personalized recommendation system, this app accurately suggests program content that aligns with the user's listening history and preferences. Users can effortlessly discover novel and intriguing radio stations and shows, enhancing their listening experience without the need for time-consuming searches.
    fontawesome_icon_name                 : user

  - title                                 : Scheduled Shutdown
    description                           : The app offers a scheduled shutdown feature, allowing users to set a specific time for automatic playback termination before bedtime. This helps conserve battery power and promotes better rest for users who enjoy listening to programs before sleep.
    fontawesome_icon_name                 : clock

  - title                                 : Multi-Device Syncing
    description                           : Users can use the same account to log in on multiple devices, ensuring that listening history, playlists, and other information synchronize seamlessly. This way, users can switch between devices effortlessly, maintaining a consistent personalized listening experience.
    fontawesome_icon_name                 : sync

  - title                                 : Program Sharing Functionality
    description                           : provides a program sharing feature, allowing users to share their favorite shows with friends via social media, messages, or email. This not only enables users to recommend great programs to their friends but also fosters communication and sharing of post-listening impressions.
    fontawesome_icon_name                 : share-nodes
  
  - title                                 : Program Recording and Replay
    description                           : Users can record their favorite programs or replay for local storage using this app. This way, users can revisit their favorite programs without an internet connection or keep recorded shows as mementos.
    fontawesome_icon_name                 : record-vinyl 

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#2C3036"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#2C3036"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
